#!/bin/sh

ARGS=3                
E_PARAM_ERR=65        

Param_Error ()        
{
  echo "Usage: `basename $0` /path/to/dvd /path/to/dvd.iso DVDTITLE"
  exit $E_PARAM_ERR
}  

if [ $# -ne "$ARGS" ] 
then
  Param_Error
fi  

dvdbackup -n $3 -M -i /dev/hda -o $1 && mkisofs -dvd-video -o $2 $1/$3 && echo $1/$3 | xargs rm -rf && echo "DVDShrink ISO Ready? set path"; read a
echo $2 | xargs rm; mkisofs -dvd-video -o $2 $a && echo $a | xargs rm -rf && eject /dev/hda && cdrecord-ProDVD -v -dao dev=/dev/hda driveropts=burnfree $2; echo "done with ripping"
echo are we done?; read b; rm $2; echo done

