#!/bin/bash

die() {
  echo "Usage: `basename $0` /path/to/dvd /path/to/dvd.iso DVDTITLE"
  exit 1
}

if [ $# -ne "3" ]; then
  die
fi

dvdbackup -n $3 -M -i /dev/hda -o $1 || die

mkisofs -dvd-video -o $2 $1/$3 || die

echo $1/$3 | xargs rm -rf || die
echo "DVDShrink ISO Ready? set path"; read path
rm -v "$2"

mkisofs -dvd-video -o $2 $path || die

rm -rf "$path" || die

eject /dev/hda || die
cdrecord-ProDVD -v -dao dev=/dev/hda driveropts=burnfree $2 || die

echo "Done with ripping & burning." && rm "$2"
